import type { LibraryVideo } from "./care-types";
import { hashPasswordSync } from "./password";
import type { AppState, Exercise } from "./types";

/** Shared demo credential hash — plaintext never stored in seed data. */
const DEMO_PASSWORD_HASH = hashPasswordSync("demo123");

export const CONDITIONS = [
  { id: "knee", label: "Knee injury" },
  { id: "back", label: "Back pain" },
  { id: "shoulder", label: "Shoulder pain" },
  { id: "hip", label: "Hip stiffness" },
  { id: "neck", label: "Neck tension" },
  { id: "ankle", label: "Ankle sprain" },
] as const;

export const GOALS = [
  "Walk without pain",
  "Return to sport",
  "Improve daily mobility",
  "Reduce stiffness",
  "Build strength safely",
  "Sleep more comfortably",
];

export const exercises: Exercise[] = [
  {
    id: "ex-knee-quad",
    name: "Seated quad set",
    condition: "knee",
    difficulty: "beginner",
    durationMin: 6,
    description: "Gently activate the thigh muscle to support the knee after injury or surgery.",
    instructions: [
      "Sit tall with the injured leg straight.",
      "Tighten the front of the thigh and press the knee down.",
      "Hold for 5 seconds, then relax.",
      "Repeat slowly without holding your breath.",
    ],
    precautions: "Stop if sharp pain, swelling, or locking occurs.",
    videoUrl: "https://videos.pexels.com/video-files/4057461/4057461-hd_1920_1080_25fps.mp4",
    thumbnail: "https://images.pexels.com/photos/8436580/pexels-photo-8436580.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    id: "ex-knee-bridge",
    name: "Glute bridge",
    condition: "knee",
    difficulty: "beginner",
    durationMin: 8,
    description: "Strengthens hips and thighs to take load off a recovering knee.",
    instructions: [
      "Lie on your back with knees bent and feet hip-width apart.",
      "Squeeze the buttocks and lift the hips.",
      "Pause at the top, then lower with control.",
    ],
    precautions: "Keep the lower back relaxed. Do not push through knee pain.",
    videoUrl: "https://videos.pexels.com/video-files/8027063/8027063-hd_1920_1080_25fps.mp4",
    thumbnail: "https://images.pexels.com/photos/3823039/pexels-photo-3823039.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    id: "ex-knee-mini-squat",
    name: "Supported mini squat",
    condition: "knee",
    difficulty: "intermediate",
    durationMin: 8,
    description: "Rebuilds functional strength for sitting and stairs.",
    instructions: [
      "Stand holding a stable chair or kitchen counter.",
      "Bend the knees a small amount, as if sitting onto a high stool.",
      "Keep knees aligned over the middle of the feet.",
      "Stand back up smoothly.",
    ],
    precautions: "Stay in a pain-free range. Avoid deep bending early on.",
    videoUrl: "https://videos.pexels.com/video-files/6453980/6453980-hd_1920_1080_25fps.mp4",
    thumbnail: "https://images.pexels.com/photos/7991662/pexels-photo-7991662.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    id: "ex-back-catcow",
    name: "Cat-cow mobility",
    condition: "back",
    difficulty: "beginner",
    durationMin: 5,
    description: "Gently moves the spine to ease stiffness and morning tightness.",
    instructions: [
      "Start on hands and knees with a neutral spine.",
      "Round the back slowly, looking toward the thighs.",
      "Then lift the chest and look forward.",
      "Move with the breath, never forcing the range.",
    ],
    precautions: "Avoid if you have acute disc pain unless cleared by your clinician.",
    videoUrl: "https://videos.pexels.com/video-files/4328304/4328304-hd_1920_1080_25fps.mp4",
    thumbnail: "https://images.pexels.com/photos/3822906/pexels-photo-3822906.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    id: "ex-back-bird",
    name: "Bird dog",
    condition: "back",
    difficulty: "intermediate",
    durationMin: 8,
    description: "Builds core stability to protect the lower back during daily tasks.",
    instructions: [
      "From hands and knees, brace the abdomen lightly.",
      "Slide one arm forward and the opposite leg back.",
      "Hold for 3 seconds without twisting the hips.",
      "Return and switch sides.",
    ],
    precautions: "Keep the spine still. Reduce range if the back arches.",
    videoUrl: "https://videos.pexels.com/video-files/4057498/4057498-hd_1920_1080_25fps.mp4",
    thumbnail: "https://images.pexels.com/photos/3823038/pexels-photo-3823038.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    id: "ex-back-walk",
    name: "Pelvic tilt",
    condition: "back",
    difficulty: "beginner",
    durationMin: 5,
    description: "Teaches gentle control of the lower back and pelvis.",
    instructions: [
      "Lie on your back with knees bent.",
      "Flatten the lower back into the floor by tilting the pelvis.",
      "Hold 5 seconds, then release.",
    ],
    precautions: "This should feel like a mild muscle effort, not a stretch into pain.",
    videoUrl: "https://videos.pexels.com/video-files/8027061/8027061-hd_1920_1080_25fps.mp4",
    thumbnail: "https://images.pexels.com/photos/4056535/pexels-photo-4056535.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    id: "ex-shoulder-pendulum",
    name: "Pendulum swing",
    condition: "shoulder",
    difficulty: "beginner",
    durationMin: 5,
    description: "Uses gravity to keep the shoulder moving with little effort.",
    instructions: [
      "Lean forward and support yourself with the other hand.",
      "Let the affected arm hang loosely.",
      "Sway the body so the arm swings in small circles.",
    ],
    precautions: "Do not actively lift the arm. Keep circles small.",
    videoUrl: "https://videos.pexels.com/video-files/6455571/6455571-hd_1920_1080_25fps.mp4",
    thumbnail: "https://images.pexels.com/photos/6111616/pexels-photo-6111616.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    id: "ex-shoulder-wall",
    name: "Wall slide",
    condition: "shoulder",
    difficulty: "intermediate",
    durationMin: 7,
    description: "Restores overhead reach with support from the wall.",
    instructions: [
      "Stand facing a wall with forearms resting on it.",
      "Slide the arms up as far as comfortable.",
      "Pause, then slide down with control.",
    ],
    precautions: "Stay below the height that causes pinching.",
    videoUrl: "https://videos.pexels.com/video-files/5385962/5385962-hd_1920_1080_25fps.mp4",
    thumbnail: "https://images.pexels.com/photos/3822621/pexels-photo-3822621.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    id: "ex-hip-clamshell",
    name: "Clamshell",
    condition: "hip",
    difficulty: "beginner",
    durationMin: 7,
    description: "Strengthens the side hip muscles that support walking.",
    instructions: [
      "Lie on your side with knees bent and feet together.",
      "Keep the pelvis still and lift the top knee.",
      "Lower slowly without rolling backward.",
    ],
    precautions: "Move from the hip, not the lower back.",
    videoUrl: "https://videos.pexels.com/video-files/8027055/8027055-hd_1920_1080_25fps.mp4",
    thumbnail: "https://images.pexels.com/photos/3822903/pexels-photo-3822903.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    id: "ex-neck-retract",
    name: "Chin tuck",
    condition: "neck",
    difficulty: "beginner",
    durationMin: 4,
    description: "Improves posture and eases desk-related neck strain.",
    instructions: [
      "Sit tall looking straight ahead.",
      "Gently draw the chin straight back, as if making a double chin.",
      "Hold 3 seconds, then relax.",
    ],
    precautions: "Do not tip the head up or down. Keep the movement small.",
    videoUrl: "https://videos.pexels.com/video-files/4498638/4498638-hd_1920_1080_25fps.mp4",
    thumbnail: "https://images.pexels.com/photos/3757942/pexels-photo-3757942.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    id: "ex-ankle-alphabet",
    name: "Ankle alphabet",
    condition: "ankle",
    difficulty: "beginner",
    durationMin: 5,
    description: "Restores ankle motion after a sprain.",
    instructions: [
      "Sit with the foot free of the floor.",
      "Draw the letters of the alphabet with the big toe.",
      "Keep letters small and smooth.",
    ],
    precautions: "Stay within a comfortable range. Ice after if swelling increases.",
    videoUrl: "https://videos.pexels.com/video-files/4761426/4761426-hd_1920_1080_25fps.mp4",
    thumbnail: "https://images.pexels.com/photos/6111575/pexels-photo-6111575.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    id: "ex-ankle-raise",
    name: "Supported heel raise",
    condition: "ankle",
    difficulty: "intermediate",
    durationMin: 6,
    description: "Rebuilds calf strength for walking and stairs.",
    instructions: [
      "Stand holding a counter.",
      "Rise onto the balls of both feet.",
      "Lower slowly to a count of three.",
    ],
    precautions: "Use both legs until your clinician progresses you.",
    videoUrl: "https://videos.pexels.com/video-files/6455576/6455576-hd_1920_1080_25fps.mp4",
    thumbnail: "https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
];

const now = Date.now();
const iso = (offsetHours: number) => new Date(now + offsetHours * 3600_000).toISOString();

export const seedState: AppState = {
  currentUserId: null,
  exercises,
  users: [
    {
      id: "physio-james",
      name: "Dr. James Okonkwo",
      email: "james@demo.physio",
      password: "",
      passwordHash: DEMO_PASSWORD_HASH,
      role: "physio",
      phone: "020 7946 0011",
      profileImageUrl: "https://images.pexels.com/photos/5215024/pexels-photo-5215024.jpeg?auto=compress&cs=tinysrgb&w=400",
      consentHipaa: true,
      consentGdpr: true,
      createdAt: iso(-720),
    },
    {
      id: "physio-aisha",
      name: "Dr. Aisha Rahman",
      email: "aisha@demo.physio",
      password: "",
      passwordHash: DEMO_PASSWORD_HASH,
      role: "physio",
      phone: "020 7946 0012",
      profileImageUrl: "https://images.pexels.com/photos/5407206/pexels-photo-5407206.jpeg?auto=compress&cs=tinysrgb&w=400",
      consentHipaa: true,
      consentGdpr: true,
      createdAt: iso(-500),
    },
    {
      id: "patient-maya",
      name: "Maya Chen",
      email: "maya@demo.physio",
      password: "",
      passwordHash: DEMO_PASSWORD_HASH,
      role: "patient",
      consentHipaa: true,
      consentGdpr: true,
      createdAt: iso(-240),
    },
    {
      id: "patient-robert",
      name: "Robert Hale",
      email: "robert@demo.physio",
      password: "",
      passwordHash: DEMO_PASSWORD_HASH,
      role: "patient",
      consentHipaa: true,
      consentGdpr: true,
      createdAt: iso(-180),
    },
    {
      id: "staff-riya",
      name: "Riya (Front desk)",
      email: "staff@demo.physio",
      password: "",
      passwordHash: DEMO_PASSWORD_HASH,
      role: "staff",
      consentHipaa: true,
      consentGdpr: true,
      createdAt: iso(-300),
    },
  ],
  profiles: [
    {
      userId: "patient-maya",
      condition: "knee",
      goal: "Walk without pain",
      diagnosis: "Right ACL reconstruction, week 6",
      painBaseline: 5,
      dateOfBirth: "1988-04-12",
      assignedPhysioId: "physio-james",
      phone: "07700 900221",
    },
    {
      userId: "patient-robert",
      condition: "back",
      goal: "Improve daily mobility",
      diagnosis: "Mechanical low back pain",
      painBaseline: 4,
      dateOfBirth: "1959-11-03",
      assignedPhysioId: "physio-james",
      phone: "07700 900334",
    },
  ],
  doctors: [
    {
      userId: "physio-james",
      clinicId: "DOC-1001",
      specialty: "Knee and sports rehabilitation",
      phone: "020 7946 0011",
      bio: "Consultant physiotherapist focusing on post-operative knee care.",
      qualifications: "HCPC, MSc Sports Physiotherapy",
      photoUrl: "https://images.pexels.com/photos/5215024/pexels-photo-5215024.jpeg?auto=compress&cs=tinysrgb&w=400",
      isVerified: true,
      location: {
        address: "12 Connaught Place, New Delhi 110001",
        city: "New Delhi",
        lat: 28.6328,
        lng: 77.2197,
      },
      availability: { days: [1, 2, 3, 4, 5], startHour: 9, endHour: 17, slotMin: 30 },
      consultationFee: 1500,
      clinicLocation: {
        latitude: 28.6328,
        longitude: 77.2197,
        address: "12 Connaught Place, New Delhi 110001",
      },
      pricing: { onlineFee: 1500, offlineFee: 1800, currency: "INR" },
    },
    {
      userId: "physio-aisha",
      clinicId: "DOC-1002",
      specialty: "Spine and chronic pain",
      phone: "020 7946 0012",
      bio: "Specialist in back, neck, and pacing programmes.",
      qualifications: "HCPC, MSc Musculoskeletal Physiotherapy",
      photoUrl: "https://images.pexels.com/photos/5407206/pexels-photo-5407206.jpeg?auto=compress&cs=tinysrgb&w=400",
      isVerified: true,
      location: {
        address: "88 Defence Colony, New Delhi 110024",
        city: "New Delhi",
        lat: 28.5733,
        lng: 77.2305,
      },
      availability: { days: [1, 2, 3, 4], startHour: 10, endHour: 16, slotMin: 30 },
      consultationFee: 1800,
      clinicLocation: {
        latitude: 28.5733,
        longitude: 77.2305,
        address: "88 Defence Colony, New Delhi 110024",
      },
      pricing: { onlineFee: 1800, offlineFee: 2200, currency: "INR" },
    },
  ],
  programs: [
    {
      id: "prog-maya",
      name: "Knee recovery — week 6",
      patientId: "patient-maya",
      physioId: "physio-james",
      startDate: iso(-168),
      status: "active",
      items: [
        { exerciseId: "ex-knee-quad", sets: 3, reps: 10, frequencyPerWeek: 7, notes: "Hold 5 seconds each." },
        { exerciseId: "ex-knee-bridge", sets: 3, reps: 8, frequencyPerWeek: 5, notes: "Pause 2 seconds at the top." },
        { exerciseId: "ex-knee-mini-squat", sets: 2, reps: 8, frequencyPerWeek: 4, notes: "Use the kitchen counter." },
      ],
    },
    {
      id: "prog-robert",
      name: "Gentle back mobility",
      patientId: "patient-robert",
      physioId: "physio-james",
      startDate: iso(-96),
      status: "active",
      items: [
        { exerciseId: "ex-back-catcow", sets: 2, reps: 8, frequencyPerWeek: 7, notes: "Morning and evening." },
        { exerciseId: "ex-back-walk", sets: 2, reps: 10, frequencyPerWeek: 6, notes: "Stop if pain radiates." },
        { exerciseId: "ex-back-bird", sets: 2, reps: 6, frequencyPerWeek: 4, notes: "Keep hips level." },
      ],
    },
  ],
  completions: [
    { id: "c1", patientId: "patient-maya", exerciseId: "ex-knee-quad", programId: "prog-maya", completedAt: iso(-50), painAfter: 3, rating: 4, comment: "Felt stable today." },
    { id: "c2", patientId: "patient-maya", exerciseId: "ex-knee-bridge", programId: "prog-maya", completedAt: iso(-48), painAfter: 3, rating: 5, comment: "Hips a bit tired." },
    { id: "c3", patientId: "patient-maya", exerciseId: "ex-knee-quad", programId: "prog-maya", completedAt: iso(-26), painAfter: 2, rating: 5, comment: "Easier than yesterday." },
    { id: "c4", patientId: "patient-maya", exerciseId: "ex-knee-mini-squat", programId: "prog-maya", completedAt: iso(-24), painAfter: 4, rating: 3, comment: "Needed the chair." },
    { id: "c5", patientId: "patient-robert", exerciseId: "ex-back-catcow", programId: "prog-robert", completedAt: iso(-20), painAfter: 3, rating: 4, comment: "Morning stiffness eased." },
  ],
  painLogs: [
    { id: "p1", patientId: "patient-maya", level: 5, note: "After a longer walk.", loggedAt: iso(-70) },
    { id: "p2", patientId: "patient-maya", level: 4, note: "Better overnight.", loggedAt: iso(-46) },
    { id: "p3", patientId: "patient-maya", level: 3, note: "After program.", loggedAt: iso(-22) },
    { id: "p4", patientId: "patient-robert", level: 4, note: "Sitting too long.", loggedAt: iso(-18) },
  ],
  consults: [
    {
      id: "call-1",
      patientId: "patient-maya",
      physioId: "physio-james",
      scheduledAt: iso(2),
      durationMin: 20,
      status: "upcoming",
      topic: "Week 6 progress review",
    },
    {
      id: "call-2",
      patientId: "patient-robert",
      physioId: "physio-james",
      scheduledAt: iso(26),
      durationMin: 30,
      status: "upcoming",
      topic: "Home setup and pacing",
    },
  ],
  bookings: [
    {
      id: "book-1",
      consultId: "call-1",
      patientId: "patient-maya",
      physioId: "physio-james",
      createdById: "patient-maya",
      patientName: "Maya Chen",
      patientEmail: "maya@demo.physio",
      patientPhone: "07700 900221",
      scheduledAt: iso(2),
      durationMin: 20,
      reason: "Week 6 progress review",
      notes: "Booked in the patient portal",
      status: "upcoming",
      createdAt: iso(-4),
      mode: "online",
      finalPrice: 1500,
      meetingLink: "/consult/call-1",
    },
    {
      id: "book-done",
      consultId: "call-done",
      patientId: "patient-maya",
      physioId: "physio-james",
      createdById: "patient-maya",
      patientName: "Maya Chen",
      patientEmail: "maya@demo.physio",
      patientPhone: "07700 900221",
      scheduledAt: iso(-48),
      durationMin: 20,
      reason: "Initial assessment",
      notes: "",
      status: "completed",
      createdAt: iso(-72),
    },
    {
      id: "book-2",
      consultId: "call-2",
      patientId: "patient-robert",
      physioId: "physio-james",
      createdById: "patient-robert",
      patientName: "Robert Hale",
      patientEmail: "robert@demo.physio",
      patientPhone: "07700 900334",
      scheduledAt: iso(26),
      durationMin: 30,
      reason: "Home setup and pacing",
      notes: "",
      status: "upcoming",
      createdAt: iso(-3),
    },
  ],
  notifications: [
    {
      id: "n1",
      userId: "patient-maya",
      title: "Time for your exercises",
      body: "3 movements are waiting in today’s program.",
      type: "exercise",
      read: false,
      createdAt: iso(-1),
      href: "/patient/program",
    },
    {
      id: "n2",
      userId: "patient-maya",
      title: "Video visit in 2 hours",
      body: "Dr. Okonkwo — Week 6 progress review.",
      type: "consult",
      read: false,
      createdAt: iso(-0.2),
      href: "/consult/call-1",
    },
    {
      id: "n3",
      userId: "physio-james",
      title: "Maya rated an exercise",
      body: "Mini squat scored 3/5 with a comment.",
      type: "feedback",
      read: false,
      createdAt: iso(-23),
      href: "/doctor/patients/patient-maya",
    },
  ],
  audit: [
    {
      id: "a1",
      at: iso(-2),
      actorId: "physio-james",
      action: "view_patient",
      detail: "Opened Maya Chen record",
    },
  ],
  reviews: [
    {
      id: "rev-maya-1",
      appointmentId: "book-done",
      patientId: "patient-maya",
      doctorId: "physio-james",
      rating: 5,
      comment: "Clear plan and careful with the knee.",
      createdAt: iso(-40),
    },
  ],
  prescriptions: [],
  dailyLogs: [
    {
      id: "dlog-1",
      patientId: "patient-maya",
      appointmentId: "book-1",
      doctorId: "physio-james",
      date: iso(-144).slice(0, 10),
      didExercises: true,
      painLevel: 6,
      note: "Stiff in the morning",
      createdAt: iso(-144),
    },
    {
      id: "dlog-2",
      patientId: "patient-maya",
      appointmentId: "book-1",
      doctorId: "physio-james",
      date: iso(-120).slice(0, 10),
      didExercises: true,
      painLevel: 5,
      note: "",
      createdAt: iso(-120),
    },
    {
      id: "dlog-3",
      patientId: "patient-maya",
      appointmentId: "book-1",
      doctorId: "physio-james",
      date: iso(-96).slice(0, 10),
      didExercises: false,
      painLevel: 5,
      note: "Travel day",
      createdAt: iso(-96),
    },
    {
      id: "dlog-4",
      patientId: "patient-maya",
      appointmentId: "book-1",
      doctorId: "physio-james",
      date: iso(-72).slice(0, 10),
      didExercises: true,
      painLevel: 4,
      note: "",
      createdAt: iso(-72),
    },
    {
      id: "dlog-5",
      patientId: "patient-maya",
      appointmentId: "book-1",
      doctorId: "physio-james",
      date: iso(-48).slice(0, 10),
      didExercises: true,
      painLevel: 4,
      note: "Better after walk",
      createdAt: iso(-48),
    },
    {
      id: "dlog-6",
      patientId: "patient-maya",
      appointmentId: "book-1",
      doctorId: "physio-james",
      date: iso(-24).slice(0, 10),
      didExercises: true,
      painLevel: 3,
      note: "",
      createdAt: iso(-24),
    },
  ],
};

export const seedVideos: LibraryVideo[] = [
  {
    id: "vid-knee-quad",
    doctorId: "physio-james",
    title: "Seated quad set",
    description: "Gently activate the thigh muscle to support the knee after injury or surgery.",
    category: "Knee Pain",
    videoUrl: "https://videos.pexels.com/video-files/4057461/4057461-hd_1920_1080_25fps.mp4",
    thumbnailUrl: "https://images.pexels.com/photos/8436580/pexels-photo-8436580.jpeg?auto=compress&cs=tinysrgb&w=800",
    duration: 360,
    createdAt: iso(-200),
    isPublic: true,
  },
  {
    id: "vid-back-catcow",
    doctorId: "physio-james",
    title: "Cat-cow mobility",
    description: "Gently moves the spine to ease stiffness and morning tightness.",
    category: "Back Stretch",
    videoUrl: "https://videos.pexels.com/video-files/4328304/4328304-hd_1920_1080_25fps.mp4",
    thumbnailUrl: "https://images.pexels.com/photos/3822906/pexels-photo-3822906.jpeg?auto=compress&cs=tinysrgb&w=800",
    duration: 300,
    createdAt: iso(-180),
    isPublic: true,
  },
  {
    id: "vid-knee-bridge",
    doctorId: "physio-aisha",
    title: "Glute bridge",
    description: "Strengthens hips and thighs to take load off a recovering knee.",
    category: "Hip Stiffness",
    videoUrl: "https://videos.pexels.com/video-files/8027063/8027063-hd_1920_1080_25fps.mp4",
    thumbnailUrl: "https://images.pexels.com/photos/3823039/pexels-photo-3823039.jpeg?auto=compress&cs=tinysrgb&w=800",
    duration: 480,
    createdAt: iso(-120),
    isPublic: true,
  },
];
